/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfirst;

import java.sql.DriverManager;

/**
 *
 * @author tishant
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student() {
        initComponents();
         book1.setText("book1 ID");
        book2.setText("book2 ID");
        book3.setText("book3 ID");
        book4.setText("book4 ID");
        book5.setText("book5 ID");
        book6.setText("book6 ID");
        roll.setText("ROLL NUMBER PLEASE");
        name.setText("NAME PLEASE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        branch = new javax.swing.JComboBox<>();
        section = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        book1 = new javax.swing.JTextField();
        book2 = new javax.swing.JTextField();
        book3 = new javax.swing.JTextField();
        book4 = new javax.swing.JTextField();
        book5 = new javax.swing.JTextField();
        book6 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        student_exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT PAGE");
        setPreferredSize(new java.awt.Dimension(1200, 800));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "1", "2", "3", "4" }));

        branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BRANCH", "CSE", "IT", "EEE", "ECE", "MECH", "IT" }));

        section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SECTION", "A", "B", "C", "D", "E", "F" }));

        name.setText("USER FULL NAME");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
        });

        roll.setText("ROLL NUMBER");
        roll.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rollFocusGained(evt);
            }
        });

        book1.setText("BOOK1");
        book1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                book1FocusGained(evt);
            }
        });
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });

        book2.setText("BOOK2");
        book2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                book2FocusGained(evt);
            }
        });

        book3.setText("BOOK3");
        book3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                book3FocusGained(evt);
            }
        });

        book4.setText("BOOK4");
        book4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                book4FocusGained(evt);
            }
        });

        book5.setText("BOOK5");
        book5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                book5FocusGained(evt);
            }
        });

        book6.setText("BOOK6");
        book6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                book6FocusGained(evt);
            }
        });

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel2.setText("                 BOOKID");

        student_exit.setText("EXIT");
        student_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_exitActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myfirst/student.jpg"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NAME");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ROLL NUMBER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(book1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addGap(331, 331, 331))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(roll, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)))
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(student_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(book1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(book2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(book3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(book4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(book5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(book6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(student_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roll, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        name.setText("");
        
    }//GEN-LAST:event_nameFocusGained
 private void nameFocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        if(name.getText().equals(""))
        name.setText("NAME PLEASE");
        
    }
    private void rollFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rollFocusGained
        // TODO add your handling code here:
        roll.setText("");
    }//GEN-LAST:event_rollFocusGained

 private void rollFocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        if(roll.getText().equals(""))
        roll.setText("NAME PLEASE");
        
    }
    private void book1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book1FocusGained
        // TODO add your handling code here:
        book1.setText("");
    }//GEN-LAST:event_book1FocusGained

 private void book1FocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        if(book1.getText().equals(""))
        book1.setText("NAME PLEASE");
        
    }
    private void book2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book2FocusGained
        // TODO add your handling code here:
        book2.setText("");
    }//GEN-LAST:event_book2FocusGained

 private void book2FocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        if(book2.getText().equals(""))
        book2.setText("NAME PLEASE");
        
    }
    private void book3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book3FocusGained
        // TODO add your handling code here:
        book3.setText("");
    }//GEN-LAST:event_book3FocusGained

 private void book3FocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        if(book3.getText().equals(""))
        book3.setText("NAME PLEASE");
        
    }
    private void book4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book4FocusGained
        // TODO add your handling code here:
        book4.setText("");
    }//GEN-LAST:event_book4FocusGained

 private void book4FocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        if(book4.getText().equals(""))
        book4.setText("NAME PLEASE");
        
    }
    private void book5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book5FocusGained
        // TODO add your handling code here:
        book5.setText("");
    }//GEN-LAST:event_book5FocusGained

 private void book5FocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        if(book5.getText()==(""))
        book5.setText("NAME PLEASE");
        
    }
    private void book6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book6FocusGained
        // TODO add your handling code here:
        book6.setText("");
    }//GEN-LAST:event_book6FocusGained
    
 private void book6FocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        if(book6.getText().equals(""))
        book6.setText("NAME PLEASE");
        
    }
    private boolean check(String n,String r,String b1,String b2,String b3,String b4,String b5,String b6,String y,String b,String s)
    {
        
        if(n.equals("USER FULL NAME") || r.equals("ROLL NUMBER") || b1.equals("BOOK1") || b2.equals("BOOK2") || b3.equals("BOOK3") || b4.equals("BOOK4") || b5.equals("BOOK5") || b6.equals("BOOK6")|| y.equals("YEAR") || b.equals("BRANCH") || s.equals("SECTION"))
        return false;
        else return true;
    }
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try
        {
            
          Class.forName("com.mysql.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost/library","root","Tishu@mysql123");
          
          PreparedStatement pt=con.prepareStatement("insert into student values(?,?,?,?,?,?,?,?,?,?,?)");
          
          String n=name.getText();
          String r=roll.getText();
          String b1=book1.getText();
          String b2=book2.getText();
          String b3=book3.getText();
          String b4=book4.getText();
          String b5=book5.getText();
          String b6=book6.getText();
          String y=(String ) year.getSelectedItem();
          String b=(String) branch.getSelectedItem();
          String s=(String) section.getSelectedItem();
          if(!check(n,r,b1,b2,b3,b4,b5,b6,y,b,s))
          {
              JOptionPane.showMessageDialog(null, "SORRY SOME FIELD NOT PROPERLY FILLED", "ALERT", JOptionPane.INFORMATION_MESSAGE);
          } 
          else {
              pt.setString(1,n);
              
              pt.setString(2,r);
              
              pt.setString(3,book1.getText());
              
              pt.setString(4,book2.getText());
              
              pt.setString(5,book3.getText());
              
              pt.setString(6,book4.getText());
              
              pt.setString(7,book5.getText());
              
              pt.setString(8,book6.getText());
              
              pt.setString(9, y);
              
              pt.setString(10, b);
              
              pt.setString(11, s);
              
              pt.executeUpdate();
            
              JOptionPane.showMessageDialog(null, "CONGRATS YOU ARE REGISTERED SUCCESSFULLY", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
            }
        pt.close();
        con.close();
        }catch(SQLException se)
        {
            System.out.println("Sorry SQL Exception found");
        }
        catch(ClassNotFoundException cnf)
        {
            System.out.println("Sorry Class Not Found Exception found");
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void student_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_exitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        welcome_1 w=new welcome_1();
        w.setVisible(true);
    }//GEN-LAST:event_student_exitActionPerformed

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField book1;
    private javax.swing.JTextField book2;
    private javax.swing.JTextField book3;
    private javax.swing.JTextField book4;
    private javax.swing.JTextField book5;
    private javax.swing.JTextField book6;
    private javax.swing.JComboBox<String> branch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name;
    private javax.swing.JTextField roll;
    private javax.swing.JComboBox<String> section;
    private javax.swing.JButton student_exit;
    private javax.swing.JButton submit;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
